### ISSUE TITLE
Best practice for library using fallible iterators?

### ISSUE THREAD

**Issue by fitzgen** [sfackler/rust-fallible-iterator#1]
I have a library that uses fallible iterators. I'd like to make them "official" by using this crate and therefore let the library's consumers get all the helper methods and all that.

But common advice I hear is not to expose another crate's types/traits unless you rename them to "hide" their origin and avoid weird dependency issues. That seems like it wouldn't work well with this library though, as you _want_ people to be able to combine different fallible iterators from different crates, right?

What's the recommended practices here?

**Comment by fitzgen** [comment]
Also: thanks for your time!

**Comment by sfackler** [comment]
The cases where you want to hide the origin of a dependency that you're exposing is when those dependencies are being used as an implementation detail. For example, if you have some type that internally uses a data structure from some third party crate and you want to add a method that iterates over the values of that data structure, you probably would want to create your own iterator type wrapping the data structure's. It's a bit more work, but avoids exposing that dependency in your public API.

In this context, though, the fact that your type implements `FallibleIterator` _is_ explicitly part of the public API. So, I wouldn't try to hide the source of that trait for the reasons you stated. One thing you could potentially do is to just reexport the `FallibleIterator` trait in your crate so people don't need to add an explicit dependency on this crate to use your iterator type.

**Comment by fitzgen** [comment]
Makes sense &mdash; thanks very much!

**Comment by sfackler** [comment]
Glad to help!
