### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by jimblandy** [sfackler/rust-fallible-iterator#16]
Could we publish today's master (11ea3bf) or thereabouts to crates.io?

(Asking for self-serving reasons; I have a crate I'd like to publish...)

**Comment by sfackler** [comment]
I think once #15 is done we can probably cut a 1.0? I'll need to look through the API again to make sure but it seems like it should be fine.

**Comment by sfackler** [comment]
0.2.0 is published. I didn't want to go all the way to 1.0 immediately after the closure type change, particularly since this is a bit like the futures-preview Stream/TryStream split.
