### ISSUE TITLE
flatten is not implemented for std Option

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [sfackler/rust-fallible-iterator#27]
The iterator method `flatten` is supported in std iterator and converts an iterator of `Option<Type>` to Type, removing all the None instances in the process. While the function `flatten` is present in the fallible-iterator crate, it's not implemented for the variant `Option<Type>`, meaning that one has to do something else. In my case, I was able to substitute it with `filter_map(Ok)`.

Minimal example where we flatten and collect in normal iterators, but doesn't work for fallible iterator (and we use `filter_map(Ok)` instead):

```
use fallible_iterator::FallibleIterator;

fn main() {
    let v1 = vec![Some(1), None, Some(2)];
    let v2 = v1.clone();
    assert_eq!(v1.into_iter().flatten().collect::<Vec<_>>(), vec![1, 2]);

    let v2_iter =
        fallible_iterator::convert(v2.into_iter().map(Ok::<_, Box<dyn std::error::Error>>));
        
    // notice we have to use filter_map(Ok) here, as flatten() doesn't work
    let result: Result<Vec<_>, _> = v2_iter.filter_map(Ok).collect();
    let result = result.unwrap();
    assert_eq!(result, vec![1, 2]);
}
```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=67d8faa68dd3a54ce53ceeabc264c603

**Comment by tamird** [comment]
The playground example works now.

@dpc I think this can be closed.
