### ISSUE TITLE
Combination of and_then and filter_map

### ISSUE THREAD

**Issue by vorner** [sfackler/rust-fallible-iterator#8]
Hello

I already noticed multiple times that I want to have a fallible map, but that I also want to skip some elements. Naturally, such closure has the `FnMut(Item) -> Result<Option<NewItem>, Error>` signature.

This can be simulated in several ways (eg. by chaining `and_then` with `filter_map(|item| item)`), but it seems a bit redundant. Does it make sense to have something like that?

**Comment by sfackler** [comment]
Yeah this is an open question I've been thinking about for a bit - see #6 for the more general problem.

**Comment by jimblandy** [comment]
Since #13 has landed, I think `filter_map` does what you want. @sfackler, should this issue be closed?

**Comment by sfackler** [comment]
Yep!
