### ISSUE TITLE
Should FromFallibleIterator::from_fallible_iterator() take an IntoFallibleIterator as an argument?

### ISSUE THREAD

**Issue by sbosnick** [sfackler/rust-fallible-iterator#9]
I am submitting this as a question rather than a suggestion because I am not sufficiently familiar with this crate to do otherwise.

This change (if appropriate) would better parallel the standard library where `FromIterator::from_iter()` takes an `IntoIterator` as its argument. This enables direct conversion from one kind of collection to another. For example:

```rust
use std::collections::LinkedList;
use std::iter::FromIterator;

fn main() {
    let v = vec!['a', 'b', 'c'];
    let ll = LinkedList::from_iter(v);
    
    println!("ll is {:?}", ll)
}
```
The blanket implementation of `IntoFallibleIterator` for all things that implement `FallibleIterator` may be enough to make this change without it being too much of a breaking change.

**Comment by sfackler** [comment]
It's unfortunately still a breaking change, since the signature of `FromFallibleIterator` changes which forces all implementations to change. It is something that we should do in the next breaking release though.

**Comment by jimblandy** [comment]
@sfackler Would this make sense to do in 0.2.0?
